In [1]:
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# for one hot encoding 
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv("../data/preprocessed/supply_chain_disruption.csv")

initial views at the data

In [4]:
df.shape

(31300, 48)

In [16]:
df.head(10)

,date,route_id,route_status,origin_country,destination_country,shipping_method,trade_route_type,distance_km,estimated_transit_days,shipping_delay_days,...,origin_iso3,destination_region,destination_event_region,destination_income_group,destination_port_capacity_index,destination_logistics_performance_index,destination_trade_dependency_score,destination_gdp_per_capita,destination_population,destination_iso3
0,01/04/2015,R1,Delayed,India,United States,Rail,Consumer Goods,8746,19,7.55,...,IND,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
1,01/11/2015,R1,Delayed,India,United States,Rail,Consumer Goods,8746,19,9.33,...,IND,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
2,01/18/2015,R1,Normal,India,United States,Rail,Consumer Goods,8746,19,3.67,...,IND,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
3,01/25/2015,R1,Delayed,India,United States,Rail,Consumer Goods,8746,19,9.22,...,IND,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
4,02/01/2015,R1,Delayed,India,United States,Rail,Consumer Goods,8746,19,6.36,...,IND,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
5,02/08/2015,R1,Delayed,India,United States,Rail,Consumer Goods,8746,19,10.61,...,IND,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
6,02/15/2015,R1,Delayed,India,United States,Rail,Consumer Goods,8746,19,7.56,...,IND,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
7,02/22/2015,R1,Delayed,India,United States,Rail,Consumer Goods,8746,19,8.22,...,IND,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
8,03/01/2015,R1,Delayed,India,United States,Rail,Consumer Goods,8746,19,8.00,...,IND,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
9,03/08/2015,R1,Normal,India,United States,Rail,Consumer Goods,8746,19,3.08,...,IND,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA

In [5]:
df.columns

Index(['date', 'route_id', 'route_status', 'origin_country',
       'destination_country', 'shipping_method', 'trade_route_type',
       'distance_km', 'estimated_transit_days', 'shipping_delay_days',
       'port_congestion_index', 'container_availability_index',
       'weather_disruption_score', 'geopolitical_risk_score',
       'trade_volume_tonnes', 'freight_cost_usd', 'carbon_emissions_tonnes',
       'origin_active_event_count', 'origin_active_event_risk',
       'destination_active_event_count', 'destination_active_event_risk',
       'covid_supply_shock_active', 'russia_ukraine_war_active',
       'events_warmup', 'fuel_cost_index', 'commodity_price_index',
       'natural_gas_price', 'steel_price', 'wheat_price', 'copper_price',
       'origin_region', 'origin_event_region', 'origin_income_group',
       'origin_port_capacity_index', 'origin_logistics_performance_index',
       'origin_trade_dependency_score', 'origin_gdp_per_capita',
       'origin_population', 'origin_iso3', 'destination_region',
       'destination_event_region', 'destination_income_group',
       'destination_port_capacity_index',
       'destination_logistics_performance_index',
       'destination_trade_dependency_score', 'destination_gdp_per_capita',
       'destination_population', 'destination_iso3'],
      dtype='object')

Dropping rows with the Disrupted routed status, as it only accounts for 3% of all total data

In [ ]:
# use the inplace=True
indices_to_drop = df[df['route_status'] == "Disrupted"].index
df.drop(indices_to_drop, inplace=True)

In [12]:
df.shape

(30302, 48)

In [15]:
df.iloc[30000:] 
# checking that data is ordered chronologically

,date,route_id,route_status,origin_country,destination_country,shipping_method,trade_route_type,distance_km,estimated_transit_days,shipping_delay_days,...,origin_iso3,destination_region,destination_event_region,destination_income_group,destination_port_capacity_index,destination_logistics_performance_index,destination_trade_dependency_score,destination_gdp_per_capita,destination_population,destination_iso3
30986,12/27/2020,R50,Normal,Brazil,United States,Sea,Consumer Goods,8070,28,3.6100,...,BRA,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
30987,01/03/2021,R50,Delayed,Brazil,United States,Sea,Consumer Goods,8070,28,10.0200,...,BRA,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
30988,01/10/2021,R50,Delayed,Brazil,United States,Sea,Consumer Goods,8070,28,10.9300,...,BRA,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
30989,01/17/2021,R50,Delayed,Brazil,United States,Sea,Consumer Goods,8070,28,9.7900,...,BRA,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
30990,01/24/2021,R50,Delayed,Brazil,United States,Sea,Consumer Goods,8070,28,7.9500,...,BRA,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31293,11/15/2026,R50,Delayed,Brazil,United States,Sea,Consumer Goods,8070,28,9.1125,...,BRA,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
31295,11/29/2026,R50,Delayed,Brazil,United States,Sea,Consumer Goods,8070,28,9.2475,...,BRA,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
31296,12/06/2026,R50,Delayed,Brazil,United States,Sea,Consumer Goods,8070,28,11.7180,...,BRA,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
31298,12/20/2026,R50,Delayed,Brazil,United States,Sea,Consumer Goods,8070,28,11.1240,...,BRA,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA
31299,12/27/2026,R50,Delayed,Brazil,United States,Sea,Consumer Goods,8070,28,10.0575,...,BRA,North America,North America,Low income,21.06,33.87,97.9,63955,250467210,USA

Count number of unique values, will need to one hot encode things

In [34]:
df.nunique()

date                                         626
route_id                                      50
route_status                                   2
origin_country                                10
destination_country                           10
shipping_method                                4
trade_route_type                               5
distance_km                                   50
estimated_transit_days                        31
shipping_delay_days                         1790
port_congestion_index                       9542
container_availability_index                4994
weather_disruption_score                    9542
geopolitical_risk_score                     9522
trade_volume_tonnes                        30154
freight_cost_usd                           29403
carbon_emissions_tonnes                    29954
origin_active_event_count                     93
origin_active_event_risk                    2455
destination_active_event_count                93
destination_active_event_risk               2454
covid_supply_shock_active                      2
russia_ukraine_war_active                      2
events_warmup                                  2
fuel_cost_index                              565
commodity_price_index                        537
natural_gas_price                            626
steel_price                                  626
wheat_price                                  626
copper_price                                 626
origin_region                                  5
origin_event_region                            4
origin_income_group                            4
origin_port_capacity_index                    10
origin_logistics_performance_index            10
origin_trade_dependency_score                 10
origin_gdp_per_capita                         10
origin_population                             10
origin_iso3                                   10
destination_region                             5
destination_event_region                       4
destination_income_group                       4
destination_port_capacity_index               10
destination_logistics_performance_index       10
destination_trade_dependency_score            10
destination_gdp_per_capita                    10
destination_population                        10
destination_iso3                              10
dtype: int64

In [37]:
wordy_cols = df.select_dtypes(include=["object"]).columns
wordy_cols

Index(['date', 'route_id', 'route_status', 'origin_country',
       'destination_country', 'shipping_method', 'trade_route_type',
       'origin_region', 'origin_event_region', 'origin_income_group',
       'origin_iso3', 'destination_region', 'destination_event_region',
       'destination_income_group', 'destination_iso3'],
      dtype='object')

In [38]:
for w in wordy_cols:
        print(f"{w}: {df[w].nunique()}")

date: 626
route_id: 50
route_status: 2
origin_country: 10
destination_country: 10
shipping_method: 4
trade_route_type: 5
origin_region: 5
origin_event_region: 4
origin_income_group: 4
origin_iso3: 10
destination_region: 5
destination_event_region: 4
destination_income_group: 4
destination_iso3: 10

get rid of: origin iso3, route id, destination iso3, desitnation region (cause its grouped and similar to destination event region)
discussed on call

In [40]:
df.drop(["route_id", "origin_iso3", "destination_iso3", "destination_region"], axis=1, inplace=True)

In [42]:
df.shape

(30302, 44)

In [43]:
df.head(10)

,date,route_status,origin_country,destination_country,shipping_method,trade_route_type,distance_km,estimated_transit_days,shipping_delay_days,port_congestion_index,...,origin_trade_dependency_score,origin_gdp_per_capita,origin_population,destination_event_region,destination_income_group,destination_port_capacity_index,destination_logistics_performance_index,destination_trade_dependency_score,destination_gdp_per_capita,destination_population
0,01/04/2015,Delayed,India,United States,Rail,Consumer Goods,8746,19,7.55,82.22,...,23.73,60735,430389014,North America,Low income,21.06,33.87,97.9,63955,250467210
1,01/11/2015,Delayed,India,United States,Rail,Consumer Goods,8746,19,9.33,72.01,...,23.73,60735,430389014,North America,Low income,21.06,33.87,97.9,63955,250467210
2,01/18/2015,Normal,India,United States,Rail,Consumer Goods,8746,19,3.67,44.64,...,23.73,60735,430389014,North America,Low income,21.06,33.87,97.9,63955,250467210
3,01/25/2015,Delayed,India,United States,Rail,Consumer Goods,8746,19,9.22,97.82,...,23.73,60735,430389014,North America,Low income,21.06,33.87,97.9,63955,250467210
4,02/01/2015,Delayed,India,United States,Rail,Consumer Goods,8746,19,6.36,73.21,...,23.73,60735,430389014,North America,Low income,21.06,33.87,97.9,63955,250467210
5,02/08/2015,Delayed,India,United States,Rail,Consumer Goods,8746,19,10.61,74.91,...,23.73,60735,430389014,North America,Low income,21.06,33.87,97.9,63955,250467210
6,02/15/2015,Delayed,India,United States,Rail,Consumer Goods,8746,19,7.56,80.74,...,23.73,60735,430389014,North America,Low income,21.06,33.87,97.9,63955,250467210
7,02/22/2015,Delayed,India,United States,Rail,Consumer Goods,8746,19,8.22,40.05,...,23.73,60735,430389014,North America,Low income,21.06,33.87,97.9,63955,250467210
8,03/01/2015,Delayed,India,United States,Rail,Consumer Goods,8746,19,8.00,56.59,...,23.73,60735,430389014,North America,Low income,21.06,33.87,97.9,63955,250467210
9,03/08/2015,Normal,India,United States,Rail,Consumer Goods,8746,19,3.08,51.89,...,23.73,60735,430389014,North America,Low income,21.06,33.87,97.9,63955,250467210

DO CORRELATION!!! (but first one hot encode route_status)

note todo, after cleaning, separate data into train and text based on dates.